blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('blog-list/', views.blog_list, name='blog_list'),
    path('blog-list/<slug:slug>/', views.blog_article, name='blog_article'),
    path('blog-list/favorite/<int:pk>/', views.blog_favorite, name='blog_favorite'),
    path('blog-favorites/', views.blog_favorites_list, name='blog_favorites_list'),
    path('blog-favorites/remove/<int:pk>/', views.blog_remove_favorite, name='blog_remove_favorite'),
]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('cart-summary/', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('order.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views


app_name = 'payment'

urlpatterns = [
    path('payment/', views.payment, name='payment'),
    path('orderplaced/', views.order_placed, name='order_placed'),
    path('webhook/', views.stripe_webhook),
]

cart/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.conf import settings
from store.models import Product
from .cart import Cart


def cart_summary(request):
    cart = Cart(request)
    return render(request, 'cart/summary.html', {'cart': cart})


def cart_add(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        cart.add(product=product, qty=product_qty)
        cartqty = cart.__len__()
        response = JsonResponse({'qty': cartqty})
        return response   


def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        cart.delete(product=product_id)
        cartqty = cart.__len__()
        carttotal = cart.get_total_price()
        response = JsonResponse({'qty': cartqty, 'subtotal': carttotal})
        return response


def cart_update(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        cart.update(product=product_id, qty=product_qty)
        cartqty = cart.__len__()
        carttotal = cart.get_total_price()
        response = JsonResponse({'qty': cartqty, 'subtotal': carttotal})
        return response


def clear(self):
    del self.session[settings.CART_SESSION_ID]
    self.save()
    

templates/cart/summary.html
{% extends "../store/base.html" %}
{% load static %}

{% block title %}
Cart Summary
{% endblock %}


{% block content %}


<!-- AJAX to update cart -->
{% block extra_head %}
<script>
  // Delete Item
  $(document).on("click", ".delete-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "cart:cart_delete" %}',
      data: {
        productid: $(this).data("index"),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();

          if(json.qty == 0){
            total = 0
            subtotal = 0
          }
          else{
            total = (parseFloat(json.subtotal) + 5.50).toFixed(2);
            subtotal = json.subtotal
          }

        document.getElementById("subtotal").innerHTML = subtotal;
        document.getElementById("cart-qty").innerHTML = json.qty;
        document.getElementById("total").innerHTML = total;
      },
      error: function (xhr, errmsg, err) {},
    });
  });

  // Update Item
  $(document).on("click", ".update-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "cart:cart_update" %}',
      data: {
        productid: $(this).data("index"),
        productqty: $("#select" + prodid + " option:selected").text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {

        total = (parseFloat(json.subtotal) + 5.50).toFixed(2);
        document.getElementById("cart-qty").innerHTML = json.qty;
        document.getElementById("subtotal").innerHTML = json.subtotal;
        document.getElementById("total").innerHTML = total;
      },
      error: function (xhr, errmsg, err) {},
    });
  });
</script>
{% endblock %}


{% if cart %}

<!-- Heading text -->
<div class="container pt-4">
  <div class="col-12">
    <div class="fw600 fs-2">Your Cart</div>
  </div>
  <div class="col-12">
    <p>Manage the <b>items</b> in your cart</p>
  </div>
  <hr />
</div>

<div class="container">
  <div class="row g-3">
    <div class="col-12 p-3 d-flex justify-content-between" style="background-color: #F3EBE3;">
      <div class="d-flex d-flex-inline">

<!-- Start of cart total -->        
        <div class="pe-3">Order</div>
        
        <div class="dropdown">
          <a class="text-reset text-decoration-none dropdown-toggle" href="#" role="link" 
            id="dropdownLink" data-bs-toggle="dropdown" aria-expanded="false">
            Shipping options
            <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" 
              class="bi bi-chevron-down" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
            </svg>
          </a>

<!-- Shipping options -->
          <ul class="dropdown-menu" aria-labelledby="dropdownLink">
            <li class="item small">5-7 day delivery</li>
            <li class="item small">Premimum delivery</li>
          </ul>
        </div>
      </div>

<!-- Subtotal -->
      <div class="text-end">
        <div>Sub total: <span>$</span>
          <div id="subtotal" class="d-inline-flex">{{cart.get_subtotal_price}}</div>
        </div>

<!-- Shipping total -->        
        <div>
          <span class="small">Shipping</span>: <span>$5.50</span>
        </div>

<!-- Total -->        
        <div class="pt-2">Total: 
          <span class="fw-bold h5">$</span><span id="total" 
          class="fw-bold h5">{{cart.get_total_price}}
          </span>
        </div>
      </div>
    </div>

<!-- Checkout button --> 
    <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
      <div class="d-grid gap-2">
        <a role="button" href="{% url 'payment:payment' %}" 
          class="btn border-dark fw-bold" type="button">Checkout
        </a>
      </div>
    </div>

<!-- Start of products in cart --> 
    <div class="col-md-7 col-lg-8 p-0">

      {% for item in cart %} 
      {% with product=item.product %}

      <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">
        <div class="row g-0 ms-4">
          <div class="col-3">

<!-- Product image --> 
            <img class="img-fluid mx-auto d-block" alt="Responsive image"
                src="{{ product.image }}" />
          </div>

          <div class="col-md-10 ps-md-3">
            <div class="card-body p-1">

<!-- Product name -->              
              <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">
                <p class="card-text pb-3">{{product.name}}</p>
              </a>

<!-- Product quantity -->
              <label for="select">Qty</label>
              <select id="select{{product.id}}" style="width:50px;height:31px;">
                <option value="" selected disabled hidden>{{item.qty}}</option>
                <option value="">1</option>
                <option value="">2</option>
                <option value="">3</option>
                <option value="">4</option>
              </select>

<!-- Update product quantity -->
              <a type="button" id="update-button" data-index="{{product.id}}" 
                class="update-button ps-3" style="color: #A38168;">
                Update
              </a>

<!-- Delete product -->
              <a type="button" id="delete-button" data-index="{{product.id}}" 
                class="delete-button ps-2" style="color: #A38168;">
                Delete
              </a>
            </div>
          </div>
        </div>
      </div>
      {% endwith %} 
      {% endfor %}
    </div>
  </div>
</div>

<!-- No items in cart -->
{% else %}
<div class="container pt-4">
  <div class="col-12">
    <div class="fw600 fs-2">Your Cart</div>
  </div>
  <div class="col-12">
    <p>You do not have any items in your cart.</p>
  </div>
  <hr />
</div>
{% endif %}

{% endblock %}