account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('registration/', views.user_registration, name='user_registration'),
    path('summary/', views.user_account_summary, name='user_account_summary'),
    path('summary/details/<int:pk>/', views.user_details, name='user_details'),
    path('summary/deletion/', views.user_account_deletion, name='user_account_deletion'),
    path('reviews/', views.user_review_list, name='user_review_list'),
    path('summary/reviews/<int:pk>/', views.user_remove_review, name='user_remove_review'),
    path('summary/reviews/<int:pk>/update/', views.user_update_review, name='user_update_review'),
    path('summary/orders/', views.user_account_orders, name='user_account_orders'),
    path('summary/favorites/', views.user_favorite_list, name='user_favorite_list'),
    path('summary/favorite/<int:pk>/', views.add_to_favorite, name='add_to_favorite'),
    path('summary/favorites/<int:pk>/remove/', views.user_remove_favorite, name='user_remove_favorite'),
]

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('blog-list/', views.blog_list, name='blog_list'),
    path('blog-list/<slug:slug>/', views.blog_article, name='blog_article'),
    path('blog-list/favorite/<int:pk>/', views.blog_favorite, name='blog_favorite'),
    path('blog-favorites/', views.blog_favorites_list, name='blog_favorites_list'),
    path('blog-favorites/remove/<int:pk>/', views.blog_remove_favorite, name='blog_remove_favorite'),
]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('cart-summary/', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('order.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views


app_name = 'store'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='home'),
    path('mission/', views.mission, name='mission'),
    path('faqs/', views.faqs, name='faqs'),
    # email sign up - not user account registration
    path('sign-up/', views.sign_up, name='sign_up'),
    path('search/', views.search_form, name='search_form'),
    path('search/result/', views.search_result, name='search_result'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
    path('store/all-products/', views.all_products, name='all_products'),
    path('store/all-products/<filter>/', views.filter_products, name='filter_products'),
    path('store/<slug:category_slug>/', views.category_list, name='category_list'),
]

templates/products/all_products.html
{% extends "store/base.html" %}
{% load static %}

{% block title %}
Products
{% endblock %}


{% block content %}

{% if messages %}
<center>
  <div class="container mt-4">
    <div class="alert alert-dark" role="alert">
      {% for message in messages %}
      <div class="alert-heading">{{ message }}</div>
      {% endfor %}
    </div>
  </div>
</center>
{% endif %}

<!-- Category filter -->
<div class="container mx-auto pt-5">
  <div class="row">
    <div class="col">
      <p>Filter By:</p>
        <ul class="nav">
          <li class="nav-item">
            <div class="dropdown">
              <div class="dropdown-toggle p-1 m-1 btn border-dark" 
                data-bs-toggle="dropdown" aria-expanded="false">
                  Category
              </div>
              <ul class="dropdown-menu">

              {% for c in categories %}
              <li {% if category.slug == c.slug %} class="selected" {% endif %}>
                <a class="dropdown-item" 
                href="{% url 'store:filter_products' filter=c.slug %}">{{ c.name | title}}</a>
              </li>
              {% endfor %}

              </ul>
            </div>
          </li>

<!-- Product feature filter -->
          <li class="nav-item">
            <div class="dropdown">
              <div class="dropdown-toggle p-1 m-1 btn border-dark"
                data-bs-toggle="dropdown" aria-expanded="false">
                  Product Feature
              </div>
              <ul class="dropdown-menu">

                {% for item in color_or_roast %}
                <li class="selected">
                    <a class="dropdown-item" 
                    href="{% url 'store:filter_products' filter=item.color_roast %}">
                    {{ item.color_roast | title}}</a>
                </li>
                {% endfor %}

              </ul>
            </div>
          </li>

<!-- Product type filter -->
          <li class="nav-item">
            <div class="dropdown">
              <div class="dropdown-toggle p-1 m-1 btn border-dark"
                data-bs-toggle="dropdown" aria-expanded="false">
                  Product Type
              </div>
              <ul class="dropdown-menu">

              <li class="selected">
                  <a class="dropdown-item" 
                  href="{% url 'store:filter_products' filter='tempered glass' %}">
                  Tempered Glass</a>
              </li>
              <li class="selected">
                <a class="dropdown-item" 
                href="{% url 'store:filter_products' filter='peruvian blend' %}">
                Peruvian Blend</a>
              </li>
              <li class="selected">
                <a class="dropdown-item" 
                href="{% url 'store:filter_products' filter='colombian blend' %}">
                Colombian Blend</a>
              </li>
              <li class="selected">
                <a class="dropdown-item" 
                href="{% url 'store:filter_products' filter='costa rica blend' %}">
                Costa Rica Blend</a>
              </li>

              </ul>
            </div>
          </li>
        </ul>
    </div>
  </div>
</div>

<!-- Start of products -->
<div class="container">
  <div class="album py-5">
    <div class="pb-3">
      <h3 class="text-center">Products</h3>
    </div>
    <div class="row row-cols-2 row-cols-md-3 g-3 justify-content-center">

      {% if products %}
      {% for product in products %}
      <div class="col">
        <div class="card border-0 pe-2 ps-2">
          <a href="{{ product.get_absolute_url }}">
            <img class="img-fluid" alt="Responsive image" 
            src="{{ product.image }}">
          </a>
          <div class="card-body px-0">
            <p class="card-text">
              <a class="text-dark text-decoration-none fw-bold" 
              href="{{ product.get_absolute_url }}">{{ product.name }}</a>
            </p>
            <div class="card-text" style="margin-top: -10px;">${{product.price}}</div>
            
            {% if product.in_stock %}
            <div class="row instock-svg">
              <div class="col">
                <svg xmlns="http://www.w3.org/2000/svg" width="45" fill="#38E54D" 
                  class="bi bi-dot" style="margin: 0px; margin-left: -18px;" viewBox="0 0 16 16">
                  <path d="M8 9.5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/>
                  <p class="card-text d-inline" style="margin-left: -10px;">In Stock</p>
                </svg>
              </div>
            </div>
    
            {% else %}
            <div class="row instock-svg">
              <div class="col">
                <svg xmlns="http://www.w3.org/2000/svg" width="45" 
                  fill="#F96666" class="bi bi-dot" style="margin: 0px; margin-left: -18px;" viewBox="0 0 16 16">
                  <path d="M8 9.5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/>
                  <p class="card-text d-inline" style="margin-left: -10px;">Out of Stock</p>
                </svg>
              </div>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

templates/products/category_list.html
{% extends "store/base.html" %}
{% load static %}

{% block title %}
{{ category.name }}
{% endblock %}


{% block content %}

<div class="container mx-auto pt-2">
  <div class="album py-5">
    <div class="pb-3">
      <h3 class="text-center">{{ category.name }}</h3>
    </div>
    <div class="row row-cols-2 row-cols-md-3 g-3 justify-content-center">

      {% if products %}
      {% for product in products %}
      <div class="col">
        <div class="card border-0 pe-2 ps-2">
          <a href="{{ product.get_absolute_url }}">
            <img class="img-fluid" alt="Responsive image" 
            src="{{ product.image }}">
          </a>
          <div class="card-body px-0">
            <p class="card-text">
              <a class="text-dark text-decoration-none fw-bold" 
              href="{{ product.get_absolute_url }}">{{ product.name }}</a>
            </p>
            <div class="card-text" style="margin-top: -10px;">${{product.price}}</div>

            {% if product.in_stock %}
            <div class="row instock-svg">
              <div class="col">
                <svg xmlns="http://www.w3.org/2000/svg" width="45" fill="#38E54D" 
                  class="bi bi-dot" style="margin: 0px; margin-left: -18px;" viewBox="0 0 16 16">
                  <path d="M8 9.5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/>
                  <p class="card-text d-inline" style="margin-left: -10px;">In Stock</p>
                </svg>
              </div>
            </div>

            {% else %}
            <div class="row instock-svg">
              <div class="col">
                <svg xmlns="http://www.w3.org/2000/svg" width="45" 
                  fill="#F96666" class="bi bi-dot" style="margin: 0px; margin-left: -18px;" viewBox="0 0 16 16">
                  <path d="M8 9.5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/>
                  <p class="card-text d-inline" style="margin-left: -10px;">Out of Stock</p>
                </svg>
              </div>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
      {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/products/single_product.html
{% extends "store/base.html" %}
{% load static %}

{% block title %}
{{ product.name }}
{% endblock %}


{% block content %}

<!-- Add to cart AJAX -->
{% block extra_head %}
<script>
    $(document).on('click', '#add-cart', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "cart:cart_add" %}',
            data: {
                productid: $('#add-cart').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
            document.getElementById("cart-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>
{% endblock %}

{% if messages %}
<center>
    <div class="container mt-4">
        <div class="alert alert-dark" role="alert">
            {% for message in messages %}
            <div class="alert-heading">{{ message }}</div>
            {% endfor %}
        </div>
    </div>
</center>
{% endif %}

<div class="container mt-3">
    <div class="row">

<!-- Product Image -->
        <div class="col-sm-12 col-md-6 d-flex justify-content-center">
            <img class="img-fluid" 
            width="350px" src="{{ product.image }}" alt="Coffio">    
        </div>

<!-- Product Name -->  
        <div class="col-sm-12 col-md-6">
            <div class="p-3 fs-3">{{ product.name }}</div>

<!-- Product Price Nested -->    
            <div class="row">
                <div class="col-6">
                    <span class="p-3 fs-5">${{ product.price }}</span>
                    <p class="text-muted ps-3">plus sales tax</p>
                </div>

<!-- Product qty nested --> 
            <div class="col-6">
                <div class="ps-3 ms-4">
                    <label for="select">Qty</label>
                    <select id="select" style="width: 50px; height: 40px;">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                    </select>
                </div>
            </div>
        </div>
        
<!-- add to cart -->
        <div class="row">
            <div class="col-sm-12 col-md-11 col-lg-10">
                <button type="button" id="add-cart" value="{{ product.id }}" 
                class="btn fw500 mt-3 w-100 add-to-cart-btn"
                data-bs-toggle="modal" data-bs-target="#checkoutModal">
                    Add to Cart
                </button>
            </div>
            
<!-- add to favorite -->
            <div class="col-sm-12 col-md-11 col-lg-10" style="margin-top: -8px;">
                <a class="btn mt-3 w-100 add-to-fav-btn" type="submit" href="{% url 'account:add_to_favorite' pk=product.id %}" 
                id="add-favorite" name="add_to_favorite" value="{{ product.id }}">Add to Favorites
                <svg id="heart-icon" xmlns="http://www.w3.org/2000/svg" width="20" fill="currentColor" 
                class="bi bi-suit-heart pe-1" viewBox="0 0 16 16">
                    <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
                </svg>{% if favorites %}
                {{ favorites }}</a>
                {% else %}</a>
                {% endif %}
            </div>
        </div>
    </div>

<!-- Modal -->
    <div class="modal fade" id="checkoutModal" tabindex="-1" aria-labelledby="checkoutModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
            
            <div class="modal-header">
                <div class="modal-title fs-5" id="checkoutModal">Added to your cart</div>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            
            <div class="modal-body">
                <div class="fs-5 fw700">{{ product.name }}</div>
                <img width="175px" src="{{ product.image }}">
                <div>${{ product.price }}</div>
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn add-to-cart-btn" data-bs-dismiss="modal">Continue Shopping</button>
                <a class="btn add-to-fav-btn" type="button" href="{% url 'cart:cart_summary' %}">View Cart and Checkout</a>
            </div>
            </div>
        </div>
    </div>    
        
<!-- Description -->
    <div class="row mt-5 d-flex justify-content-center">
        <div class="col-sm-12 col-lg-11">
            <div class="fs-5 fw-bold pb-2">Description</div>
            <p>{{ product.description }}</p>
        </div>
    </div>

<!-- 2nd product image -->

<!-- if statement checks if product is cup or beans, if cup - display
    the 2nd image, if coffee beans - only display feature with 
    adjusted styling. -->
{% if product.height %}
    <div class="row mt-3 justify-content-center">
        <div class="col-sm-12 col-md-6 d-flex justify-content-center">

            {% for i in images %}
            {% if forloop.first %}
                <img class="img-fluid" 
                width="350px" src="{{ i.image.url }}" alt="Coffio">
            {% endif %}
            {% endfor %}
        </div>

<!-- Features -->
        {% else %}
        <div class="col-12 ms-lg-5">
        {% endif %}
        <div class="col-sm-12 col-md-6">
            <div class="fs-5 fw-bold pb-2 pt-3">Features</div>
            <ul>
                <li>Made from {{ product.material_features | capfirst }}</li>
                
                {% if product.height %}
                <li>Height {{ product.height }}"</li>
                {% else %}
                {% endif %}
                <li>Volume {{ product.volume }} oz</li>
            <ul>
        </div>
    </div>  

<!-- User reviews --> 
    <div class="row">
        <div class="col-sm-12 col-lg-10 ms-lg-4">
            <div class="fs-5 fw-bold pb-2 mt-5">Reviews</div>
            {% if average %}
            <div class="mb-2">Average customer rating 
                
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" 
                fill="#F3E0B5" class="bi bi-star-fill ms-2" viewBox="0 0 16 16" style="margin-top: -4px;">
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                </svg> {{ average | floatformat:'1' }}
                {% else %}
                {% endif %}
            </div>
        </div>
    </div>
        <hr>

<!-- Start of reviews -->
        {% if reviews %}
        {% for review in reviews %}
        <div class="row border-bottom">
            <div class="col-sm-3 col-lg-5 ms-lg-4 mt-2">
                <div class="mb-0">{{ review.username }}</div>
                <div class="mt-2">{{ review.created | date:"M d, Y"}}</div>
            </div>
            <div class="col-sm-3 col-md-6 mt-2">
                <p class="mb-0">{{ review.stars }}
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" 
                    fill="#F3E0B5" class="bi bi-star-fill ms-2" viewBox="0 0 16 16" style="margin-top: -4px;">
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                </svg>
                </p>
                <p class="mb-0 mt-3">{{ review.review }}</p>
                <div class="mb-0 mt-3 mb-4">Recommends this product 
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" 
                    fill="#1F1913" class="bi bi-check-lg" viewBox="0 0 16 16">
                        <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
                    </svg> Yes
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="row">
            <div class="col-sm-5 mt-2 ms-lg-4">
                <div>There are no reviews for this product, be the first to leave a review!</div>
            </div>
        </div>
        {% endif %}

<!-- Review Form -->
        {% if user.is_authenticated %}
        <form method="post" action="">
            
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-4 mt-2 ms-lg-4">
                    <div class="fs-5 fw-bold pb-2 pt-3 mt-3 justify-content-left">Write a Review</div>
                </div>
            </div>
                
                <div class="row">
                    <div class="col-5 col-lg-4 ms-lg-4">
                        <!-- username -->
                        <label for="username" class="form-label">{{ form.username.label }}</label>
                        <input readonly type="text" class="form-control mb-3" name="username" 
                        placeholder="" value="{{ user.username }}">
                    </div>
                    <div class="col-5 col-lg-4 ms-lg-4">
                        <div class="form-check">
                            <div class="col-auto my-1">
                                <!-- stars -->
                                <label class="mr-sm-2 mb-1" for="stars">{{ form.stars.label }}</label>
                                <select class="custom-select mr-sm-2" name="stars" required>
                                <option selected>Choose...</option>
                                <option name="stars" value="5">5</option>
                                <option name="stars" value="4">4</option>
                                <option name="stars" value="3">3</option>
                                <option name="stars" value="2">2</option>
                                <option name="stars" value="1">1</option>
                                </select>
                                <div class="invalid-feedback">
                                    Please choose a star rating.
                                </div>
                            </div>
                        </div>        
                    </div>
                </div>
                <div class="row">
                    <div class="col-11 col-lg-10 ms-lg-4">
                        <!-- review text -->
                        <label for="review" class="form-label">{{ form.review.label }}</label>
                        <textarea class="form-control" name="review" rows="3" required></textarea>
                        <div class="invalid-feedback">
                            Review is required.
                        </div>
                    </div>
                </div>         

            <input type="submit" class="btn add-to-fav-btn ps-5 pe-5 mt-3 ms-lg-4" value="Submit">
        </form>
        {% else %}
        <div class="mt-2 ms-lg-4">Please <a href="{% url 'account:user_login' %}" 
            style="color: #A38168;">login</a> to leave a review.</div>
        {% endif %}

{% endblock %}