blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('blog-list/', views.blog_list, name='blog_list'),
    path('blog-list/<slug:slug>/', views.blog_article, name='blog_article'),
    path('blog-list/favorite/<int:pk>/', views.blog_favorite, name='blog_favorite'),
    path('blog-favorites/', views.blog_favorites_list, name='blog_favorites_list'),
    path('blog-favorites/remove/<int:pk>/', views.blog_remove_favorite, name='blog_remove_favorite'),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('order.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from account.models import CustomUser
from django.urls import reverse


class BlogMedia(models.Model):
    """
    Creates media for blog posts.
    """
    image = models.ImageField(upload_to='blog/')
    is_default = models.BooleanField(default=True)

    class Meta: 
        verbose_name = "blog image"
        verbose_name_plural = "blog images"
    
    def __str__(self):
        return self.image.url


class BlogManager(models.Manager):
    """
    Manager returns only blog posts that have been set to publish.
    """
    def get_queryset(self):
        return super(BlogManager, self).get_queryset().filter(status=1)


# Choices for Blog model
STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Blog(models.Model):
    """
    Creates Blog posts created by admin users.
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS, default=0)
    image = models.ForeignKey(BlogMedia, on_delete=models.CASCADE)
    favorite = models.ManyToManyField(CustomUser, related_name="user_favorites", blank=True)
    blogs = BlogManager() 

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        return reverse("blog:blog_article", args=[self.slug])

    def get_favorites(slug):
        """
        Returns integer for number of users who have favorited a blog post
        based on blog post slug.
        """
        favorites = Blog.blogs.get(slug=slug)
        return favorites.favorite.count()

    def __str__(self):
        return self.title

blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from blog.models import Blog


def blog_list(request):
    blog_list = Blog.blogs.all()
    return render(request, 'blog/blog.html', {'blog_list': blog_list})


def blog_article(request, slug):
    article = get_object_or_404(Blog, slug=slug, status=1)
    favorites = Blog.get_favorites(slug)
    return render(request, 'blog/article.html', {'article': article, 'favorites': favorites})


@login_required 
def blog_favorite(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    if blog.favorite.filter(id=request.user.id):
        blog.favorite.remove(request.user.id)
    else:
        blog.favorite.add(request.user.id)  
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def blog_favorites_list(request):
    blog_list = Blog.blogs.filter(favorite=request.user)
    return render(request, 'account/user_blog_favorites.html', {'blog_list': blog_list})


@login_required
def blog_remove_favorite(request, pk):
    blog = Blog.blogs.get(pk=pk)
    blog.favorite.filter(id=request.user.id)
    blog.favorite.remove(request.user.id)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

templates/blog/article.html
{% extends "store/base.html" %}
{% load static %}

{% block title %}
{{ blog.title }}
{% endblock %}


{% block content %}

<main class="container p-4">
    <div class="col-md-10">
        <article class="blog-post">
            <h2 class="blog-post-title mb-3">{{ article.title }}</h2>
            <div class="blog-post-meta mb-3">{{ article.created | date:"M d, Y" }} by {{ article.author | capfirst }}</div>
            
            <a class="btn mt-2 add-to-fav-btn" type="submit" 
            href="{% url 'blog:blog_favorite' pk=article.id %}" id="add-favorite" 
            name="add_to_favorite" value="{{ article.id }}">Add to Favorites
            <svg id="heart-icon" xmlns="http://www.w3.org/2000/svg" width="20" fill="currentColor" 
                class="bi bi-suit-heart pe-1" viewBox="0 0 16 16">
                <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
            </svg>{% if favorites %}
            <span>{{ favorites }}</span></a>
            {% else %}</a>
            {% endif %}

            <p class="mt-4">{{ article.content }}</p>
        </article>
    </div>
</main>
  
{% endblock %}

templates/blog/blog.html
{% extends "store/base.html" %}
{% load static %}

{% block title %}
Coffio Blog
{% endblock %}


{% block content %}

{% for blog in blog_list %}
<div class="container mt-3">
  <div class="row mb-2">
    <div class="col-md-12 col-lg-7">
      <div class="row g-0 border rounded overflow-hidden 
      flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0">{{ blog.title }}</h3>
          <div class="mb-1 text-muted">{{ blog.created | date:"M d, Y" }}</div>
          <p class="card-text mb-auto">{{ blog.content | slice:'0:75' }}...</p>
          <a href="{{ blog.get_absolute_url }}" style="color: #A38168;" 
          class="stretched-link">Continue reading</a>
        </div>
        <div class="col-auto d-none d-sm-block">
          <img class="img" src="{{ blog.image }}" width="200" 
          height="250" role="img" focusable="false"></img>
        </div>
      </div>
    </div>
  </div>
</div>
{% endfor %}

{% endblock %}