account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('registration/', views.user_registration, name='user_registration'),
    path('summary/', views.user_account_summary, name='user_account_summary'),
    path('summary/details/<int:pk>/', views.user_details, name='user_details'),
    path('summary/deletion/', views.user_account_deletion, name='user_account_deletion'),
    path('reviews/', views.user_review_list, name='user_review_list'),
    path('summary/reviews/<int:pk>/', views.user_remove_review, name='user_remove_review'),
    path('summary/reviews/<int:pk>/update/', views.user_update_review, name='user_update_review'),
    path('summary/orders/', views.user_account_orders, name='user_account_orders'),
    path('summary/favorites/', views.user_favorite_list, name='user_favorite_list'),
    path('summary/favorite/<int:pk>/', views.add_to_favorite, name='add_to_favorite'),
    path('summary/favorites/<int:pk>/remove/', views.user_remove_favorite, name='user_remove_favorite'),
]

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('blog-list/', views.blog_list, name='blog_list'),
    path('blog-list/<slug:slug>/', views.blog_article, name='blog_article'),
    path('blog-list/favorite/<int:pk>/', views.blog_favorite, name='blog_favorite'),
    path('blog-favorites/', views.blog_favorites_list, name='blog_favorites_list'),
    path('blog-favorites/remove/<int:pk>/', views.blog_remove_favorite, name='blog_remove_favorite'),
]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('cart-summary/', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('order.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views


app_name = 'store'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='home'),
    path('mission/', views.mission, name='mission'),
    path('faqs/', views.faqs, name='faqs'),
    # email sign up - not user account registration
    path('sign-up/', views.sign_up, name='sign_up'),
    path('search/', views.search_form, name='search_form'),
    path('search/result/', views.search_result, name='search_result'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
    path('store/all-products/', views.all_products, name='all_products'),
    path('store/all-products/<filter>/', views.filter_products, name='filter_products'),
    path('store/<slug:category_slug>/', views.category_list, name='category_list'),
]

store/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from account.models import CustomUser


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta: 
        verbose_name_plural = "Categories"

    def get_absolute_url(self):
        return reverse("store:category_list", args=[self.slug])

    def __str__(self):
        return self.name


class Color(models.Model):
    color_roast = models.CharField(
        max_length=150, 
        help_text='Please enter coffee cup color or coffee bean roast.'
    )

    class Meta:
        verbose_name_plural = "Color variants"

    def __str__(self):
        return self.color_roast


class Media(models.Model):
    image = models.ImageField(upload_to='images/')
    product_association = models.CharField(max_length=150, blank=False)
    is_default = models.BooleanField(default=True)

    class Meta: 
        verbose_name = "product image"
        verbose_name_plural = "product images"
    
    def get_product_images(product_association):
        """
        A function that returns all images based on the product's assigned
        association, such as color or blend.
        """
        product_images = Media.objects.filter(product_association=product_association)
        return product_images
        
    def __str__(self):
        return self.image.url


class ProductManager(models.Manager):
    """
    Product manager returns all products that have been set to is_active = True.
    """
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


# Choices for the material_features field in the Product model
PRODUCT_MATERIAL_FEATURES = (
    ('tempered glass', 'tempered glass'),
    ('colombian blend', 'colombian blend'),
    ('peruvian blend', 'peruvian blend'),
    ('costa rica blend', 'costa rica blend')
)


class Product(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    description = models.TextField(blank=True)
    sku = models.IntegerField(db_index=True, unique=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    sale_price = models.DecimalField(max_digits=5, decimal_places=2)
    image = models.ForeignKey(
        Media, 
        help_text='Upload a product image', 
        on_delete=models.CASCADE
    )
    color_roast = models.ForeignKey(Color, on_delete=models.CASCADE)
    material_features = models.CharField(
        choices=PRODUCT_MATERIAL_FEATURES, 
        max_length=25
    )
    height = models.IntegerField(blank=True, null=True)
    volume = models.IntegerField(blank=True)
    stock_qty = models.IntegerField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        related_name='product_creator', 
        on_delete=models.CASCADE
    )
    slug = models.SlugField(max_length=255)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    favorite = models.ManyToManyField(
        CustomUser, 
        related_name="favorites", 
        blank=True
    ) 
    products = ProductManager()

    class Meta: 
        verbose_name_plural = "Products"
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])

    def total_favorites(slug):
        item = Product.products.get(slug=slug)
        return item.favorite.count()
  
    def __str__(self):
        return self.name


class Reviews(models.Model):
    # choices for stars field
    RATINGS = [
        (5, 5), 
        (4, 4), 
        (3, 3),
        (2, 2),
        (1, 1)
    ]
    user = models.ManyToManyField(CustomUser)
    username = models.TextField(blank=True)
    review = models.TextField(max_length=2000, blank=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    stars = models.IntegerField(
        choices=RATINGS,
        default=5,
        blank=True
    )
    verified = models.BooleanField(default=True)

    class Meta: 
        verbose_name = "User review"
        verbose_name_plural = "User reviews"

    def get_average_rating(pk):
        """
        A function for returning the average star rating
        based on an individual product.
        """
        reviews = Reviews.objects.filter(product=pk).values('stars')
        if reviews:
            sum = 0
            count = 0

            for stars in reviews:
                star = stars.get('stars')
                sum = sum + int(star)
                count += 1
            
            avg = sum / count
            return avg 
        else:
            return None

    def match(request, current_product_id):
        """
        A function that creates a list of users who have reviewed current product. 
        Function checks if current user has left a review, prevents multiple
        reviews being made by one user.
        """
        queryset = Reviews.objects.filter(product=current_product_id).values('username')
        review_usernames = []

        if queryset:
            for i in queryset:
                queryset_username = i.get('username')
                review_usernames.append(queryset_username)
        else:
            return False
        if request.user.username in review_usernames:
            return True
        else: 
            return False

    def __str__(self):
        return self.review


class EmailList(models.Model):
    """
    A model for collecting sign up emails.
    """
    email = models.EmailField(blank=True)

store/forms.py
from django import forms
from .models import EmailList, Reviews


class ReviewForm(forms.ModelForm):
    """
    A form for users to create a review for a specific product.
    """
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "name": "username"
            }
        )
    )
    review = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "name": "review"
            }
        )
    )
    stars = forms.IntegerField(
        required=True,
        error_messages={
            'required': 'Please choose a rating.',
            'invalid': 'Please choose a rating.'
        },
        widget=forms.Select(
            attrs={
                "class": "form-check",
                "name": "stars"
            }
        )
    )
    created = forms.DateTimeField(
        required=False
    )
    verified = forms.BooleanField(
        required=False
    )
    class Meta:
        model = Reviews
        fields = [
            'username',
            'review',
            'stars',
        ]


class EmailListForm(forms.ModelForm):
    """
    A form to capture users that sign up for the email list.
    """
    email = forms.EmailField() 

    class Meta:
        model = EmailList
        fields = ['email']
        

store/views.py
from django.http import HttpResponseRedirect
from django.views import generic
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse
from .models import Product, Media, Reviews, Category
from .forms import ReviewForm, EmailListForm
from store.product_filters import category_filter


class ProductListView(generic.ListView):
    model = Product
    context_object_name = 'product_list'
    queryset = Product.products.all().order_by('-name')[0:4]
    template_name = 'store/home.html'

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['reviews'] = Reviews.objects.all()[0:4]
        return context


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    images = Media.get_product_images(product.image.product_association)
    favorites = Product.total_favorites(slug)
    average = Reviews.get_average_rating(pk=product.id)
    reviews = Reviews.objects.filter(product=product.id)  
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            previous_review = Reviews.match(request, product.id)
            if previous_review == True:
                messages.error(request, 'This username has already created a review for this product.')
                return redirect(reverse('store:product_detail', kwargs={'slug': slug}))
            else:
                review = form.save(commit=False)
                review.product = product
                review.save()
                messages.success(request, "Your review has been submitted!")
                return redirect(reverse('store:product_detail', kwargs={'slug': slug}))
    else:
        form = ReviewForm()
    return render(request, 'products/single_product.html', {
        'product': product, 
        'images': images, 
        'form': form, 
        'average': average, 
        'favorites': favorites,
        'reviews': reviews
    })


def all_products(request):
    products = Product.products.all()
    return render(request, 'products/all_products.html', {'products': products})


def filter_products(request, filter):
    products = category_filter(filter)
    if products:
        return render(request, 'products/all_products.html', {'products': products})
    else:
        messages.error(request, 'No items where found.')
        return render(request, 'products/all_products.html')


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.products.filter(category=category)
    return render(request, 'products/category_list.html', {'category': category, 'products': products})


# Email sign up list - not user account registration       
def sign_up(request):
    if request.method == 'POST':
        form = EmailListForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path_info)
    else:
        form = EmailListForm()
    return render(request, 'account/account_summary.html', {'form': form})


def search_form(request):
    return render(request, 'store/search_form.html')


def search_result(request):
    if request.method == 'POST':
        search_input = request.POST['search_input']
        if search_input:
            search_results = Product.products.filter(name__contains=search_input)
            return render(request, 'store/search_result.html', {
                'search_input': search_input, 
                'search_results': search_results
            })
        else:
            messages.error(request, "Sorry, there are no results for that search.")
            return render(request, 'store/search_result.html')
    else:
        return render(request, 'store/search_result.html')
        

def mission(request):
    return render(request, 'store/resources/mission.html')


def faqs(request):
    return render(request, 'store/resources/faqs.html')
    

templates/store/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Coffio{% endblock %}</title>
        {% load static %}
        <link rel="shortcut icon" type="image/png" href="{% static 'store/img/coffio-logo.png' %}">
        <!-- Meta -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Portfolio">
        <meta name="author" content="Vanessa Wingardh">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
        </script>
        {% block extra_head %}{% endblock %}
        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'store/base.css' %}">
        <link rel="stylesheet" href="{% static 'cart/cart.css' %}">
        <link rel="icon" href="{% static 'store/coffio-favicon.png' %}">
    </head>

    <body>
        <header>
            <!-- Start of navbar -->
            <nav class="navbar navbar-expand-md">
                <div class="container-fluid">
                    
                    <!-- Brand logo -->
                    <a class="navbar-brand d-flex-inline me-0" href="/">
                        <img src="{% static 'store/coffio-logo.png' %}" width="150" alt="logo">
                    </a>
                    
                    <!-- Navbar toggle --> 
                    <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" 
                    data-bs-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" 
                    aria-label="Toggle navigation">
                        <div class="navbar-toggler-icon"></div>
                    </button>
                        
                    <div class="collapse navbar-collapse" id="navbarToggler">
                        
                    <!-- Navbar items -->
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        
                        <!-- Shop nav -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" 
                                aria-expanded="false">
                                Shop
                                <i class="ps-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                        fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd"
                                            d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
                                    </svg>
                                </i>
                            </a>
                            
                            <!-- Nested all products -->
                            <ul class="dropdown-menu rounded-3 border-1" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" href="{% url 'store:all_products' %}">
                                        All Products
                                    </a>
                                </li>
                                
                                <!-- Nested categories -->
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">
                                        {{ c.name|title }}
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                        
                        <!-- Mission nav -->                        
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'store:mission' %}">Mission</a>
                        </li>
                        
                        <!-- FAQs nav -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'store:faqs' %}">FAQs</a>
                        </li>
                        
                        <!-- Brew blog nav -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:blog_list' %}">Brew Blog</a>
                        </li>
                    </ul>

                    <!-- Search -->
                    <a type="button" role="button" href="{% url 'store:search_form' %}"
                        class="btn btn-outline-secondary border-0 cart-btn nav-auth">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" 
                                class="bi bi-search" viewBox="0 0 16 16">
                                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                            </svg>
                        </div>
                        <span>Search</span>
                    </a>

                    <!-- Logout -->
                    <!-- if user authenticated - show logout and account nav -->
                    {% if request.user.is_authenticated %}
                    <a type="button" role="button" href="{% url 'account:user_logout' %}"
                        class="btn btn-outline-secondary border-0 cart-btn nav-auth">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-door-closed" viewBox="0 0 16 16">
                                <path
                                    d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                                <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                            </svg>
                        </div>
                        <span>Logout</span>
                    </a>

                    <!-- Account -->
                    <a type="button" role="button" href="{% url 'account:user_account_summary' %}"
                        class="btn btn-outline-secondary border-0 cart-btn nav-auth">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-person" viewBox="0 0 16 16">
                                <path
                                    d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                            </svg>
                        </div>
                        <span>Account</span>
                    </a>

                    <!-- Lpgin -->
                    <!-- if user not authenticated - show login and sign up nav -->
                    {% else %}
                    <a type="button" role="button" href="{% url 'account:user_login' %}"
                        class="btn btn-outline-secondary border-0 cart-btn nav-auth">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-door-closed" viewBox="0 0 16 16">
                                <path
                                    d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                                <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                            </svg>
                        </div>
                        <span>Login</span>
                    </a>
                    
                    <!-- Sign up -->   
                    <a type="button" role="button" href="{% url 'account:user_registration' %}"
                        class="btn btn-outline-secondary border-0 cart-btn nav-auth">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" 
                            class="fa fa-user-plus" viewBox="0 0 640 512">
                                <path d="M352 128c0 70.7-57.3 128-128 128s-128-57.3-128-128S153.3 0 224 0s128 57.3 128 128zM0 482.3C0 383.8 79.8 304 178.3 304h91.4C368.2 304 448 383.8 448 482.3c0 16.4-13.3 29.7-29.7 29.7H29.7C13.3 512 0 498.7 0 482.3zM504 312V248H440c-13.3 0-24-10.7-24-24s10.7-24 24-24h64V136c0-13.3 10.7-24 24-24s24 10.7 24 24v64h64c13.3 0 24 10.7 24 24s-10.7 24-24 24H552v64c0 13.3-10.7 24-24 24s-24-10.7-24-24z" />
                                <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                            </svg>
                        </div>
                        <span>Sign Up</span>
                    </a>
                    {% endif %}

                    <!-- Cart --> 
                    <a type="button" role="button" href="{% url "cart:cart_summary" %}"
                        class="btn btn-outline-secondary border-0 cart-btn nav-auth">

                        {% with total_qty=cart|length %}
                        <div id="cart-qty" class="cart-qty">
                            
                            {% if total_qty > 0 %}
                            {{ total_qty }}
                            {% else %}
                            0
                            {% endif %}
                        </div>
                        {% endwith %}
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-cart3" viewBox="0 0 16 16">
                                <path
                                    d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                            </svg>
                        </div>
                        <span>Cart</span>
                    </a>
                </div>
            </nav>
        </header>

        <!-- Templates content -->
        <div id="content">{% block content %} {% endblock %}</div>

        <!-- Footer -->
        <footer class="container py-5 footer">
            <hr>
            <div class="row pt-2">
                
                <!-- Logo -->
                <div class="col-12 col-md">
                    <img src="{% static 'store/coffio-logo.png' %}" width="150" alt="logo" style="margin-left: -25px;">
                </div>
                <div class="col-6 col-md">
                    <h5>Resources</h5>
                    <ul class="list-unstyled">
                        <li><a class="link-secondary text-decoration-none" href="#">Customer service</a></li>
                        <li><a class="link-secondary text-decoration-none" href="#">Returns</a></li>
                        <li><a class="link-secondary text-decoration-none" href="#">Team feature</a></li>
                        <li><a class="link-secondary text-decoration-none" href="#">Price guarantee</a></li>
                        <li><a class="link-secondary text-decoration-none" href="#">Terms of use</a></li>
                        <li><a class="link-secondary text-decoration-none" href="#">Privacy and security</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>About Us</h5>
                    <ul class="list-unstyled">
                        <li><a class="link-secondary text-decoration-none" href="#">Team</a></li>
                        <li><a class="link-secondary text-decoration-none" href="#">Mission</a></li>
                        <li><a class="link-secondary text-decoration-none" href="#">Reviews</a></li>
                        <li><a class="link-secondary text-decoration-none" href="#">FAQs</a></li>
                        <li><a class="link-secondary text-decoration-none" href="#">Work with us</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </body>
</html>

templates/store/search_form.html
{% extends 'store/base.html' %}
{% load static %}

{% block title %}
Coffio
{% endblock %}


{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-6">
            <form id="search-form" method="post" action="{% url 'store:search_result' %}" 
                class="d-flex align-items-center border border-dark rounded" role="search">
                {% csrf_token %}
                <input class="form-control" type="search" placeholder="What are you looking for?" 
                aria-label="Search" name="search_input">
                <button class="btn btn-outline-success ms-2" type="submit">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" 
                        class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                    </svg>
                </button>
            </form>
        </div>
    </div>
</div>

{% endblock %}